### ISSUE TITLE
some time logs not saving in log file

### ISSUE THREAD

**Issue by Ananthageethan** [ltpitt/bash-network-repair-automation#10]
![WhatsApp Image 2022-01-29 at 9 07 45 PM](https://user-images.githubusercontent.com/65566377/151667115-48ef24ee-0b5a-4edb-a2a4-6859fdcca2a4.jpeg)

after 5 netcheck its successfully restarting wlan0, but in this case 23.26 watch this time in log file after this log next 6.24 in next day log is only there in log file, 
what happen pi between 23.26 to 6.24 ? 

note : i was tested this script in raspberrypi board runing 24/7.

**Comment by ltpitt** [comment]
Hello there and thanks for using the script.

Please explain a bit more, how are you running the script?

**Comment by Ananthageethan** [comment]
yes i running crontab every minute to write log, but less chance to power outage bcz we are using 24/7 with UPS power support.

**Comment by ltpitt** [comment]
Is this happening every day or it only happened once?

**Comment by Ananthageethan** [comment]
happened 2 days or 3 days once, still i'm not find out what is exact problem..

i mostly used raspberry pi access through anydesk only,
