### ISSUE TITLE
Reboot cycles are not prevented with file on /tmp

### ISSUE THREAD

**Issue by La-te** [ltpitt/bash-network-repair-automation#11]
I have set the `reboot_server=true`. However, as the /tmp/.last_net_autoboot is on /tmp it gets removed on reboot and does not exist ever after the reboot. Hence, the `reboot_cycle=60` is not really effective. /tmp is cleaned on reboot at least on Raspberry Pi OS.

Another note. The `network_check_threshold=5` can be quite short. On my environment there might be easily four failures after the network reset by the script. The script is looping in some 20 seconds those attempts.

**Comment by ltpitt** [comment]
Hello there!

Thanks for using the script and for the valuable feedback.

The threshold can easily be adjusted changing the number.
Doing so we allow people using different environments to adapt the
functionality quickly.
In any case I will put a higher number by default as per your suggestion.

I will investigate about your tmp issue and find a solution, I will keep
you posted!

**Comment by ltpitt** [comment]
Hi @La-te,

I have updated the script, would you mind testing the new version?
Please let me know if I can close this issue once done :)

Thanks for your help and feedback to make the script better!

**Comment by ltpitt** [comment]
Hello there,

In case you don't provide a reply in a few days I will consider the issue solved and close it.

Have a nice day!
