### ISSUE TITLE
`/bin/sh: 1: Cannot fork` Memory leak?

### ISSUE THREAD

**Issue by d4rken** [ltpitt/bash-network-repair-automation#12]
After a while the log file contained hundreds of `/bin/sh: 1: Cannot fork` lines.
The network connection is very spotty, so it's possible the script triggered a lot.

Running in a Pi Zero W 2 using https://github.com/ltpitt/bash-network-repair-automation/commit/02c5fc5c70ecf0fc33875795656018bf12733ef8

`5.10.63-v7+ #1496 SMP Wed Dec 1 15:58:11 GMT 2021 armv7l` `Raspbian GNU/Linux 10 (buster)`

**Comment by ltpitt** [comment]
Hello there and thanks for using this script!

If your connection is quite unreliable I would suggest you to run the script less often, for example every 5 minutes:
5 * * * * /yourpath/network_check.sh >> /var/log/netcheck.log 2>&1

Another thing that comes to my mind is that this flooding of logs maybe filled your disk?

Can you check with:
`df -h`
?

**Comment by d4rken** [comment]
> Hello there and thanks for using this script!

Thanks for making it, and the quick response :heart:.

> If your connection is quite unreliable I would suggest you to run the script less often, for example every 5 minutes:
> 5 * * * * /yourpath/network_check.sh >> /var/log/netcheck.log 2>&1

Will do. This happened after a few weeks of running.

> Another thing that comes to my mind is that this flooding of logs maybe filled your disk?
> 
> Can you check with: `df -h` ?

```bash
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        59G  2.2G   54G   4% /
devtmpfs        182M     0  182M   0% /dev
tmpfs           214M  4.0K  214M   1% /dev/shm
tmpfs           214M   40M  175M  19% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           214M     0  214M   0% /sys/fs/cgroup
/dev/mmcblk0p1  253M   49M  204M  20% /boot
tmpfs            32M   28K   32M   1% /var/cache/fontconfig
tmpfs            43M     0   43M   0% /run/user/1000
```

**Comment by ltpitt** [comment]
It is my pleasure :)

Disk space is more than fine, I suspect that given the continous network problems the script ended up running while other instances of it were running too.

I hope that changing the frequency will fix it...
Please keep me posted!

**Comment by ltpitt** [comment]
Hello, @d4rken !

I hope all is good :)

Was this issue solved, can I close it?

**Comment by d4rken** [comment]
I'm not sure the root cause is fixed, but the previous issue took weeks to manifest, with the new timing it might be month (and only if WiFi is spotty again).

Let's close this as I don't think currently warrants taking up more of your head space, if it happens again I'll re-open and others can find this now too via search if they encounter something similar :+1: 

Thanks for the quick answers, have a great week!
