### ISSUE TITLE
Sorry but ifupdown is not installed. Aborting.

### ISSUE THREAD

**Issue by pentium90** [ltpitt/bash-network-repair-automation#3]
This happens on rpi zero w, fixed by:
command -v **/sbin/ifup** >/dev/null 2>&1 || { echo >&2 "Sorry but ifupdown is not installed. Aborting.";  exit 1; }

cat /etc/debian_version
10.1

also on rpi model b
cat /etc/debian_version
9.11

**Comment by ltpitt** [comment]
Very strange!

I will add a fix to support also your scenario, thanks for reporting :)

``command -v /sbin/ifup >/dev/null 2>&1 || command -v ifup >/dev/null 2>&1` || { echo >&2 "Sorry but fping is not installed. Aborting.";  exit 1; }`
