### ISSUE TITLE
Raspbian does not appear to contain /etc/default/rcS anymore

### ISSUE THREAD

**Issue by deltabravozulu** [ltpitt/bash-network-repair-automation#4]
Per [your instructions](https://github.com/ltpitt/bash-network-repair-automation#optional---automatic-repair-with-fsck-in-case-of-reboot), /etc/default/rcS does not appear to exist on a Raspberry Pi 2 running Raspbian 10 (Buster).

**Comment by deltabravozulu** [comment]
As it turns out, it now lives in `/lib/init/vars.sh `

**Comment by ltpitt** [comment]
Great info and thanks for reporting it, @deltabravozulu !

I will immediately update the README.md :)
