### ISSUE TITLE
-mtime option on test for reboot

### ISSUE THREAD

**Issue by pcchynoweth** [ltpitt/bash-network-repair-automation#9]
The find command on line 73 in network_check.sh uses the -mtime option with a value of 60 for reboot_cycle. When I read the documentation for the find command it looks like it won't reboot unless the last boot was more than 60 days ago, rather than 60 minutes ago (which I assume was the intention). I think the option should be -mmin

**Comment by ltpitt** [comment]
Hi there,

Sorry for the late reply and thanks for your input!

You are indeed right, great catch.

I am fixing it right away :)
